// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type ActiveToken struct {
	Sub int32
	Jti string
}

type Answer struct {
	ID         int32
	Body       string
	Votes      int32
	QuestionID int32
	UserID     int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Question struct {
	ID            int32
	Title         string
	Body          string
	PriorityLevel int32
	UserID        int32
	RespondedAt   time.Time
	Closed        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	Points    int32
	Credits   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Vote struct {
	ID        int32
	Val       int32
	AnswerID  int32
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
